import { createContext, useContext, useState, ReactNode } from "react";

export type Locale = "fr" | "it" | "de" | "en" | "rm";

const translations: Record<Locale, Record<string, string>> = {
  fr: {
    hero_title: "Knowledge-to-Learning Engine",
    hero_subtitle: "Transformez votre documentation interne en formations intelligentes",
    select_role: "Choisissez votre profil",
    rbac: "RBAC – Contrôle d'accès basé sur les rôles",
    admin_title: "Administrateur",
    admin_desc: "Créez des formations, définissez les sources, gérez les accès",
    user_title: "Collaborateur",
    user_desc: "Suivez vos formations, personnalisez vos objectifs, jeux de rôle",
    invite_title: "Inviter un participant",
    invite_desc: "Générer un lien d'invitation",
    invite_copy: "Copier le lien",
    invite_copied: "Lien copié !",
    invite_email_placeholder: "email@exemple.com",
    invite_send: "Envoyer l'invitation",
    enter: "Accéder",
    feat_ai: "Génération IA",
    feat_rag: "Moteur RAG",
    feat_tenant: "Multi-tenant",
    feat_swiss: "Hébergement Suisse",
    arch_title: "Architecture Client / Serveur",
    arch_client: "Client (Frontend)",
    arch_client_desc: "React + Vite exécuté dans le navigateur de l'utilisateur. Interface d'interaction avec l'IA.",
    arch_server: "Serveur (Backend)",
    arch_server_desc: "Hébergé chez Infomaniak (Suisse), Ubuntu Server, API sécurisée, moteur RAG.",
    footer: "Conçu en Suisse",
    login_title: "Connexion",
    login_email: "Adresse e-mail",
    login_password: "Mot de passe",
    login_submit: "Se connecter",
    login_back: "Retour à l'accueil",
    login_error: "Échec de connexion",
    login_error_desc: "Email ou mot de passe incorrect",
    login_test_mode: "Mode test — authentification locale (JSON)",
    access_restricted: "Accès réservé aux membres",
    download: "Télécharger",
    // Sidebar
    nav_dashboard: "Tableau de bord",
    nav_formations: "Formations",
    nav_documents: "Documents",
    nav_evaluations: "Évaluations",
    nav_roleplay: "Jeu de rôle",
    nav_analytics: "Analytics",
    nav_users: "Utilisateurs",
    nav_settings: "Paramètres",
    nav_invite: "Inviter",
    role_guest: "invité",
    nav_logout: "Déconnexion",
    // Dashboard
    dashboard_title: "Tableau de bord",
    dashboard_subtitle: "Vue d'ensemble de votre Knowledge Engine",
    dashboard_subtitle_guest: "Vos formations et évaluations",
    stat_active_learners: "Apprenants actifs",
    stat_active_formations: "Formations actives",
    stat_indexed_docs: "Documents indexés",
    stat_avg_score: "Score moyen",
    stat_change_month: "+12% ce mois",
    stat_change_week: "+3 cette semaine",
    stat_new_docs: "82 nouveaux",
    stat_vs_last_month: "+5% vs mois dernier",
    stat_assigned: "assignées",
    formations_in_progress: "Formations en cours",
    active: "actives",
    modules: "modules",
    recent_activity: "Activité récente",
    quick_generate: "Générer une formation",
    quick_generate_desc: "À partir de vos documents",
    quick_analytics: "Voir les analytics",
    quick_analytics_desc: "Performance des équipes",
    quick_roleplay: "Lancer un jeu de rôle",
    quick_roleplay_desc: "Simulation interactive",
    quick_invite: "Inviter un participant",
    quick_invite_desc: "Lien d'invitation externe",
    // Documents
    docs_title: "Documents",
    docs_subtitle: "Bibliothèque documentaire & base vectorielle",
    docs_import: "Importer",
    docs_search: "Rechercher un document...",
    docs_filter: "Filtrer",
    docs_drop_zone: "Glissez vos fichiers ici ou cliquez pour importer",
    docs_drop_subtitle: "PDF, DOCX, PPTX, Wiki — Max 50MB par fichier",
    docs_generate_training: "Générer une formation",
    docs_generate_desc: "Décrivez la formation à créer à partir de vos documents importés",
    docs_chat_placeholder: "Ex : Créer une formation sécurité réseau à partir des documents IT...",
    col_document: "Document",
    col_service: "Service",
    col_size: "Taille",
    col_chunks: "Chunks",
    col_status: "Statut",
    col_date: "Date",
    col_actions: "Actions",
    status_indexed: "Indexé",
    status_pending: "En cours",
    pii_anonymized: "🛡️ Données anonymisées",
    pii_replaced: "PII remplacées",
    // Formations
    formations_title: "Formations",
    formations_subtitle: "Parcours générés automatiquement par l'IA",
    formations_generate: "Générer une formation",
    formations_readonly: "Lecture seule",
    formations_admin_only: "Réservé aux admins",
    status_active: "Active",
    status_draft: "Brouillon",
    participants: "participants",
    // Evaluations
    eval_title: "Évaluations",
    eval_next: "Suivant",
    eval_finish: "Terminer",
    eval_restart: "Recommencer",
    eval_success: "Excellent ! Vous maîtrisez ce module.",
    eval_fail: "Des axes d'amélioration ont été identifiés.",
    eval_correct: "Correct",
    eval_incorrect: "Incorrect",
    eval_question: "Question",
    // Roleplay
    roleplay_title: "Jeu de rôle",
    roleplay_subtitle: "Simulation interactive basée sur vos procédures internes",
    roleplay_placeholder: "Votre action ou réponse...",
    // Analytics
    analytics_title: "Analytics",
    analytics_subtitle: "Performance et suivi des compétences",
    analytics_completion_rate: "Taux de complétion",
    analytics_avg_time: "Temps moyen",
    analytics_active_users: "Utilisateurs actifs",
    analytics_global_progress: "Progression globale",
    analytics_service_perf: "Performance par service",
    analytics_skills_map: "Cartographie des compétences",
    analytics_skills_desc: "Détection automatique des lacunes par service",
    analytics_completion: "Complétion",
    analytics_avg_score: "score moy.",
    analytics_active: "actifs",
  },
  it: {
    hero_title: "Knowledge-to-Learning Engine",
    hero_subtitle: "Trasforma la documentazione interna in formazioni intelligenti",
    select_role: "Scegli il tuo profilo",
    rbac: "RBAC – Controllo degli accessi basato sui ruoli",
    admin_title: "Amministratore",
    admin_desc: "Crea formazioni, definisci le fonti, gestisci gli accessi",
    user_title: "Collaboratore",
    user_desc: "Segui le formazioni, personalizza i tuoi obiettivi, giochi di ruolo",
    invite_title: "Invita un partecipante",
    invite_desc: "Genera un link d'invito",
    invite_copy: "Copia il link",
    invite_copied: "Link copiato!",
    invite_email_placeholder: "email@esempio.com",
    invite_send: "Invia l'invito",
    enter: "Accedi",
    feat_ai: "Generazione IA",
    feat_rag: "Motore RAG",
    feat_tenant: "Multi-tenant",
    feat_swiss: "Hosting Svizzera",
    arch_title: "Architettura Client / Server",
    arch_client: "Client (Frontend)",
    arch_client_desc: "React + Vite eseguito nel browser dell'utente. Interfaccia di interazione con l'IA.",
    arch_server: "Server (Backend)",
    arch_server_desc: "Ospitato da Infomaniak (Svizzera), Ubuntu Server, API sicura, motore RAG.",
    footer: "Progettato in Svizzera",
    login_title: "Accesso",
    login_email: "Indirizzo e-mail",
    login_password: "Password",
    login_submit: "Accedi",
    login_back: "Torna alla home",
    login_error: "Accesso fallito",
    login_error_desc: "Email o password errati",
    login_test_mode: "Modalità test — autenticazione locale (JSON)",
    access_restricted: "Accesso riservato ai membri",
    download: "Scarica",
    nav_dashboard: "Dashboard",
    nav_formations: "Formazioni",
    nav_documents: "Documenti",
    nav_evaluations: "Valutazioni",
    nav_roleplay: "Gioco di ruolo",
    nav_analytics: "Analytics",
    nav_users: "Utenti",
    nav_settings: "Impostazioni",
    nav_invite: "Invita",
    role_guest: "ospite",
    nav_logout: "Disconnetti",
    dashboard_title: "Dashboard",
    dashboard_subtitle: "Panoramica del Knowledge Engine",
    dashboard_subtitle_guest: "Le tue formazioni e valutazioni",
    stat_active_learners: "Studenti attivi",
    stat_active_formations: "Formazioni attive",
    stat_indexed_docs: "Documenti indicizzati",
    stat_avg_score: "Punteggio medio",
    stat_change_month: "+12% questo mese",
    stat_change_week: "+3 questa settimana",
    stat_new_docs: "82 nuovi",
    stat_vs_last_month: "+5% vs mese scorso",
    stat_assigned: "assegnate",
    formations_in_progress: "Formazioni in corso",
    active: "attive",
    modules: "moduli",
    recent_activity: "Attività recente",
    quick_generate: "Genera una formazione",
    quick_generate_desc: "Dai tuoi documenti",
    quick_analytics: "Vedi analytics",
    quick_analytics_desc: "Performance dei team",
    quick_roleplay: "Avvia un gioco di ruolo",
    quick_roleplay_desc: "Simulazione interattiva",
    quick_invite: "Invita un partecipante",
    quick_invite_desc: "Link d'invito esterno",
    docs_title: "Documenti",
    docs_subtitle: "Libreria documentale & base vettoriale",
    docs_import: "Importa",
    docs_search: "Cerca un documento...",
    docs_filter: "Filtra",
    docs_drop_zone: "Trascina i tuoi file qui o clicca per importare",
    docs_drop_subtitle: "PDF, DOCX, PPTX, Wiki — Max 50MB per file",
    docs_generate_training: "Genera una formazione",
    docs_generate_desc: "Descrivi la formazione da creare dai tuoi documenti importati",
    docs_chat_placeholder: "Es: Crea una formazione sulla sicurezza di rete dai documenti IT...",
    col_document: "Documento",
    col_service: "Servizio",
    col_size: "Dimensione",
    col_chunks: "Chunks",
    col_status: "Stato",
    col_date: "Data",
    col_actions: "Azioni",
    status_indexed: "Indicizzato",
    status_pending: "In corso",
    pii_anonymized: "🛡️ Dati anonimizzati",
    pii_replaced: "PII sostituite",
    formations_title: "Formazioni",
    formations_subtitle: "Percorsi generati automaticamente dall'IA",
    formations_generate: "Genera una formazione",
    formations_readonly: "Solo lettura",
    formations_admin_only: "Riservato agli admin",
    status_active: "Attiva",
    status_draft: "Bozza",
    participants: "partecipanti",
    eval_title: "Valutazioni",
    eval_next: "Successivo",
    eval_finish: "Termina",
    eval_restart: "Ricomincia",
    eval_success: "Eccellente! Hai padroneggiato questo modulo.",
    eval_fail: "Sono stati identificati degli assi di miglioramento.",
    eval_correct: "Corretto",
    eval_incorrect: "Sbagliato",
    eval_question: "Domanda",
    roleplay_title: "Gioco di ruolo",
    roleplay_subtitle: "Simulazione interattiva basata sulle tue procedure interne",
    roleplay_placeholder: "La tua azione o risposta...",
    analytics_title: "Analytics",
    analytics_subtitle: "Performance e monitoraggio delle competenze",
    analytics_completion_rate: "Tasso di completamento",
    analytics_avg_time: "Tempo medio",
    analytics_active_users: "Utenti attivi",
    analytics_global_progress: "Progresso globale",
    analytics_service_perf: "Performance per servizio",
    analytics_skills_map: "Mappa delle competenze",
    analytics_skills_desc: "Rilevamento automatico delle lacune per servizio",
    analytics_completion: "Completamento",
    analytics_avg_score: "punt. medio",
    analytics_active: "attivi",
  },
  de: {
    hero_title: "Knowledge-to-Learning Engine",
    hero_subtitle: "Verwandeln Sie Ihre interne Dokumentation in intelligente Schulungen",
    select_role: "Wählen Sie Ihr Profil",
    rbac: "RBAC – Rollenbasierte Zugriffskontrolle",
    admin_title: "Administrator",
    admin_desc: "Schulungen erstellen, Quellen definieren, Zugriffe verwalten",
    user_title: "Mitarbeiter",
    user_desc: "Schulungen verfolgen, Ziele personalisieren, Rollenspiele",
    invite_title: "Teilnehmer einladen",
    invite_desc: "Einladungslink generieren",
    invite_copy: "Link kopieren",
    invite_copied: "Link kopiert!",
    invite_email_placeholder: "email@beispiel.com",
    invite_send: "Einladung senden",
    enter: "Zugreifen",
    feat_ai: "KI-Generierung",
    feat_rag: "RAG-Engine",
    feat_tenant: "Multi-Tenant",
    feat_swiss: "Schweizer Hosting",
    arch_title: "Client / Server Architektur",
    arch_client: "Client (Frontend)",
    arch_client_desc: "React + Vite im Browser des Benutzers. Interaktionsschnittstelle mit KI.",
    arch_server: "Server (Backend)",
    arch_server_desc: "Gehostet bei Infomaniak (Schweiz), Ubuntu Server, sichere API, RAG-Engine.",
    footer: "Entwickelt in der Schweiz",
    login_title: "Anmeldung",
    login_email: "E-Mail-Adresse",
    login_password: "Passwort",
    login_submit: "Anmelden",
    login_back: "Zurück zur Startseite",
    login_error: "Anmeldung fehlgeschlagen",
    login_error_desc: "E-Mail oder Passwort falsch",
    login_test_mode: "Testmodus — lokale Authentifizierung (JSON)",
    access_restricted: "Zugang nur für Mitglieder",
    download: "Herunterladen",
    nav_dashboard: "Dashboard",
    nav_formations: "Schulungen",
    nav_documents: "Dokumente",
    nav_evaluations: "Bewertungen",
    nav_roleplay: "Rollenspiel",
    nav_analytics: "Analytics",
    nav_users: "Benutzer",
    nav_settings: "Einstellungen",
    nav_invite: "Einladen",
    role_guest: "Gast",
    dashboard_title: "Dashboard",
    dashboard_subtitle: "Übersicht Ihrer Knowledge Engine",
    dashboard_subtitle_guest: "Ihre Schulungen und Bewertungen",
    stat_active_learners: "Aktive Lernende",
    stat_active_formations: "Aktive Schulungen",
    stat_indexed_docs: "Indexierte Dokumente",
    stat_avg_score: "Durchschnittsnote",
    stat_change_month: "+12% diesen Monat",
    stat_change_week: "+3 diese Woche",
    stat_new_docs: "82 neue",
    stat_vs_last_month: "+5% gg. letzten Monat",
    stat_assigned: "zugewiesen",
    formations_in_progress: "Laufende Schulungen",
    active: "aktiv",
    modules: "Module",
    recent_activity: "Letzte Aktivität",
    quick_generate: "Schulung generieren",
    quick_generate_desc: "Aus Ihren Dokumenten",
    quick_analytics: "Analytics anzeigen",
    quick_analytics_desc: "Teamleistung",
    quick_roleplay: "Rollenspiel starten",
    quick_roleplay_desc: "Interaktive Simulation",
    quick_invite: "Teilnehmer einladen",
    quick_invite_desc: "Externer Einladungslink",
    docs_title: "Dokumente",
    docs_subtitle: "Dokumentenbibliothek & Vektordatenbank",
    docs_import: "Importieren",
    docs_search: "Dokument suchen...",
    docs_filter: "Filtern",
    docs_drop_zone: "Dateien hierher ziehen oder zum Importieren klicken",
    docs_drop_subtitle: "PDF, DOCX, PPTX, Wiki — Max 50MB pro Datei",
    docs_generate_training: "Schulung generieren",
    docs_generate_desc: "Beschreiben Sie die Schulung aus Ihren importierten Dokumenten",
    docs_chat_placeholder: "Z.B.: Eine Netzwerksicherheitsschulung aus IT-Dokumenten erstellen...",
    col_document: "Dokument",
    col_service: "Abteilung",
    col_size: "Größe",
    col_chunks: "Chunks",
    col_status: "Status",
    col_date: "Datum",
    col_actions: "Aktionen",
    status_indexed: "Indexiert",
    status_pending: "In Bearbeitung",
    pii_anonymized: "🛡️ Daten anonymisiert",
    pii_replaced: "PII ersetzt",
    formations_title: "Schulungen",
    formations_subtitle: "Automatisch von KI generierte Lernpfade",
    formations_generate: "Schulung generieren",
    formations_readonly: "Nur Lesen",
    formations_admin_only: "Nur für Admins",
    status_active: "Aktiv",
    status_draft: "Entwurf",
    participants: "Teilnehmer",
    eval_title: "Bewertungen",
    eval_next: "Weiter",
    eval_finish: "Abschließen",
    eval_restart: "Neustart",
    eval_success: "Ausgezeichnet! Sie beherrschen dieses Modul.",
    eval_fail: "Es wurden Verbesserungsbereiche identifiziert.",
    eval_correct: "Richtig",
    eval_incorrect: "Falsch",
    eval_question: "Frage",
    roleplay_title: "Rollenspiel",
    roleplay_subtitle: "Interaktive Simulation basierend auf Ihren internen Verfahren",
    roleplay_placeholder: "Ihre Aktion oder Antwort...",
    analytics_title: "Analytics",
    analytics_subtitle: "Leistung und Kompetenzmonitoring",
    analytics_completion_rate: "Abschlussrate",
    analytics_avg_time: "Durchschnittszeit",
    analytics_active_users: "Aktive Benutzer",
    analytics_global_progress: "Gesamtfortschritt",
    analytics_service_perf: "Leistung nach Abteilung",
    analytics_skills_map: "Kompetenzkarte",
    analytics_skills_desc: "Automatische Lückenerkennung nach Abteilung",
    analytics_completion: "Abschluss",
    analytics_avg_score: "Durchschn.",
    analytics_active: "aktiv",
  },
  en: {
    hero_title: "Knowledge-to-Learning Engine",
    hero_subtitle: "Transform your internal documentation into intelligent training",
    select_role: "Choose your profile",
    rbac: "RBAC – Role-Based Access Control",
    admin_title: "Administrator",
    admin_desc: "Create training, define sources, manage access",
    user_title: "Collaborator",
    user_desc: "Follow your training, customize your goals, roleplay",
    invite_title: "Invite a participant",
    invite_desc: "Generate an invitation link",
    invite_copy: "Copy link",
    invite_copied: "Link copied!",
    invite_email_placeholder: "email@example.com",
    invite_send: "Send invitation",
    enter: "Enter",
    feat_ai: "AI Generation",
    feat_rag: "RAG Engine",
    feat_tenant: "Multi-tenant",
    feat_swiss: "Swiss Hosting",
    arch_title: "Client / Server Architecture",
    arch_client: "Client (Frontend)",
    arch_client_desc: "React + Vite running in the user's browser. AI interaction interface.",
    arch_server: "Server (Backend)",
    arch_server_desc: "Hosted by Infomaniak (Switzerland), Ubuntu Server, secure API, RAG engine.",
    footer: "Made in Switzerland",
    login_title: "Login",
    login_email: "Email address",
    login_password: "Password",
    login_submit: "Sign in",
    login_back: "Back to home",
    login_error: "Login failed",
    login_error_desc: "Incorrect email or password",
    login_test_mode: "Test mode — local authentication (JSON)",
    access_restricted: "Access restricted to members",
    download: "Download",
    nav_dashboard: "Dashboard",
    nav_formations: "Training",
    nav_documents: "Documents",
    nav_evaluations: "Assessments",
    nav_roleplay: "Roleplay",
    nav_analytics: "Analytics",
    nav_users: "Users",
    nav_settings: "Settings",
    nav_invite: "Invite",
    role_guest: "guest",
    dashboard_title: "Dashboard",
    dashboard_subtitle: "Overview of your Knowledge Engine",
    dashboard_subtitle_guest: "Your training and assessments",
    stat_active_learners: "Active learners",
    stat_active_formations: "Active training",
    stat_indexed_docs: "Indexed documents",
    stat_avg_score: "Average score",
    stat_change_month: "+12% this month",
    stat_change_week: "+3 this week",
    stat_new_docs: "82 new",
    stat_vs_last_month: "+5% vs last month",
    stat_assigned: "assigned",
    formations_in_progress: "Training in progress",
    active: "active",
    modules: "modules",
    recent_activity: "Recent activity",
    quick_generate: "Generate training",
    quick_generate_desc: "From your documents",
    quick_analytics: "View analytics",
    quick_analytics_desc: "Team performance",
    quick_roleplay: "Start roleplay",
    quick_roleplay_desc: "Interactive simulation",
    quick_invite: "Invite a participant",
    quick_invite_desc: "External invitation link",
    docs_title: "Documents",
    docs_subtitle: "Document library & vector database",
    docs_import: "Import",
    docs_search: "Search a document...",
    docs_filter: "Filter",
    docs_drop_zone: "Drag your files here or click to import",
    docs_drop_subtitle: "PDF, DOCX, PPTX, Wiki — Max 50MB per file",
    docs_generate_training: "Generate training",
    docs_generate_desc: "Describe the training to create from your imported documents",
    docs_chat_placeholder: "E.g.: Create a network security training from IT documents...",
    col_document: "Document",
    col_service: "Service",
    col_size: "Size",
    col_chunks: "Chunks",
    col_status: "Status",
    col_date: "Date",
    col_actions: "Actions",
    status_indexed: "Indexed",
    status_pending: "Pending",
    pii_anonymized: "🛡️ Data anonymized",
    pii_replaced: "PII replaced",
    formations_title: "Training",
    formations_subtitle: "AI-generated learning paths",
    formations_generate: "Generate training",
    formations_readonly: "Read only",
    formations_admin_only: "Admin only",
    status_active: "Active",
    status_draft: "Draft",
    participants: "participants",
    eval_title: "Assessments",
    eval_next: "Next",
    eval_finish: "Finish",
    eval_restart: "Restart",
    eval_success: "Excellent! You've mastered this module.",
    eval_fail: "Areas for improvement have been identified.",
    eval_correct: "Correct",
    eval_incorrect: "Incorrect",
    eval_question: "Question",
    roleplay_title: "Roleplay",
    roleplay_subtitle: "Interactive simulation based on your internal procedures",
    roleplay_placeholder: "Your action or response...",
    analytics_title: "Analytics",
    analytics_subtitle: "Performance and skills monitoring",
    analytics_completion_rate: "Completion rate",
    analytics_avg_time: "Average time",
    analytics_active_users: "Active users",
    analytics_global_progress: "Global progress",
    analytics_service_perf: "Performance by service",
    analytics_skills_map: "Skills map",
    analytics_skills_desc: "Automatic gap detection by service",
    analytics_completion: "Completion",
    analytics_avg_score: "avg. score",
    analytics_active: "active",
  },
  rm: {
    hero_title: "Knowledge-to-Learning Engine",
    hero_subtitle: "Transfurmai vossa documentaziun interna en furmaziuns intelligentas",
    select_role: "Tschernai voss profil",
    rbac: "RBAC – Controlla d'access basada sin rols",
    admin_title: "Administratur",
    admin_desc: "Creai furmaziuns, definai las funtaunas, administrai ils access",
    user_title: "Collavuratur",
    user_desc: "Suandai vossas furmaziuns, persunalisai voss finamiras, gieus da rols",
    invite_title: "Invitar in participant",
    invite_desc: "Generar ina colliaziun d'invitaziun",
    invite_copy: "Copiar la colliaziun",
    invite_copied: "Colliaziun copiada!",
    invite_email_placeholder: "email@exempel.com",
    invite_send: "Trametter l'invitaziun",
    enter: "Entrar",
    feat_ai: "Generaziun IA",
    feat_rag: "Motor RAG",
    feat_tenant: "Multi-tenant",
    feat_swiss: "Hosting Svizzer",
    arch_title: "Architectura Client / Server",
    arch_client: "Client (Frontend)",
    arch_client_desc: "React + Vite exequì en il navigatur da l'utilisader. Interfatscha d'interacziun cun l'IA.",
    arch_server: "Server (Backend)",
    arch_server_desc: "Ospità tar Infomaniak (Svizra), Ubuntu Server, API segira, motor RAG.",
    footer: "Creà en Svizra",
    login_title: "Annunzia",
    login_email: "Adressa d'e-mail",
    login_password: "Pled-clav",
    login_submit: "S'annunziar",
    login_back: "Enavos a la pagina principala",
    login_error: "Annunzia fallida",
    login_error_desc: "E-mail u pled-clav incorrect",
    login_test_mode: "Modus da test — autentificaziun locala (JSON)",
    access_restricted: "Access reservà als commembers",
    download: "Telechargiar",
    nav_dashboard: "Survista",
    nav_formations: "Furmaziuns",
    nav_documents: "Documents",
    nav_evaluations: "Evaluaziuns",
    nav_roleplay: "Gieu da rols",
    nav_analytics: "Analytics",
    nav_users: "Utilisaders",
    nav_settings: "Parameters",
    nav_invite: "Invitar",
    role_guest: "ospita",
    dashboard_title: "Survista",
    dashboard_subtitle: "Survista da voss Knowledge Engine",
    dashboard_subtitle_guest: "Vossas furmaziuns ed evaluaziuns",
    stat_active_learners: "Emprendiders activs",
    stat_active_formations: "Furmaziuns activas",
    stat_indexed_docs: "Documents indexads",
    stat_avg_score: "Punct. mesaun",
    stat_change_month: "+12% quest mais",
    stat_change_week: "+3 questa emna",
    stat_new_docs: "82 novs",
    stat_vs_last_month: "+5% vs mais passà",
    stat_assigned: "attribuidas",
    formations_in_progress: "Furmaziuns en cours",
    active: "activas",
    modules: "moduls",
    recent_activity: "Activitad recenta",
    quick_generate: "Generar ina furmaziun",
    quick_generate_desc: "Da voss documents",
    quick_analytics: "Mussar analytics",
    quick_analytics_desc: "Prestaziuns da las equipas",
    quick_roleplay: "Lantschar in gieu da rols",
    quick_roleplay_desc: "Simulaziun interactiva",
    quick_invite: "Invitar in participant",
    quick_invite_desc: "Colliaziun d'invitaziun externa",
    docs_title: "Documents",
    docs_subtitle: "Biblioteca da documents & basa vectoriala",
    docs_import: "Importar",
    docs_search: "Tschertgar in document...",
    docs_filter: "Filtrar",
    docs_drop_zone: "Trai voss documents qua u cliccar per importar",
    docs_drop_subtitle: "PDF, DOCX, PPTX, Wiki — Max 50MB per document",
    docs_generate_training: "Generar ina furmaziun",
    docs_generate_desc: "Descrivai la furmaziun da crear da voss documents importads",
    docs_chat_placeholder: "P.ex.: Crear ina furmaziun da segirezza da rait dals documents IT...",
    col_document: "Document",
    col_service: "Servetsch",
    col_size: "Grondezza",
    col_chunks: "Chunks",
    col_status: "Status",
    col_date: "Data",
    col_actions: "Acziuns",
    status_indexed: "Indexà",
    status_pending: "En lavur",
    pii_anonymized: "🛡️ Datas anonimisadas",
    pii_replaced: "PII remplazzadas",
    formations_title: "Furmaziuns",
    formations_subtitle: "Percurs generads automaticamain da l'IA",
    formations_generate: "Generar ina furmaziun",
    formations_readonly: "Mo leger",
    formations_admin_only: "Reservà als admins",
    status_active: "Activa",
    status_draft: "Sboz",
    participants: "participants",
    eval_title: "Evaluaziuns",
    eval_next: "Proxim",
    eval_finish: "Terminar",
    eval_restart: "Recumenzar",
    eval_success: "Excellent! Vus duminais quest modul.",
    eval_fail: "Axas da meglieraziun èn vegnidas identifitgadas.",
    eval_correct: "Correct",
    eval_incorrect: "Incorrect",
    eval_question: "Dumonda",
    roleplay_title: "Gieu da rols",
    roleplay_subtitle: "Simulaziun interactiva basada sin vossas proceduras internas",
    roleplay_placeholder: "Vossa acziun u resposta...",
    analytics_title: "Analytics",
    analytics_subtitle: "Prestaziun e monitoring da las cumpetenzas",
    analytics_completion_rate: "Quota da cumplettaziun",
    analytics_avg_time: "Temp mesaun",
    analytics_active_users: "Utilisaders activs",
    analytics_global_progress: "Progress global",
    analytics_service_perf: "Prestaziun per servetsch",
    analytics_skills_map: "Carta da las cumpetenzas",
    analytics_skills_desc: "Detecziun automatica da las lacunas per servetsch",
    analytics_completion: "Cumplettaziun",
    analytics_avg_score: "punct. mes.",
    analytics_active: "activs",
  },
};

interface LanguageContextType {
  locale: Locale;
  setLocale: (l: Locale) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [locale, setLocale] = useState<Locale>("fr");
  const t = (key: string) => translations[locale]?.[key] ?? key;
  return (
    <LanguageContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};